export const ADD_MOVIE_FAVORITES = "ADD_MOVIE_FAVORITES";
export const DEL_MOVIE_FAVORITES = "DEL_MOVIE_FAVORITES";
export const FETCH_FAVORITES = "FETCH_FAVORITES";

// попытка переноса функций поиска в Redux
export const SEARCH_MOVIES_REQUEST = "SEARCH_MOVIES_REQUEST"
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS"
export const SEARCH_MOVIES_FAILURE = "SEARCH_MOVIES_FAILURE"